hashuk_dmytro_javarush_project_2_inhabited_island
dmitrijgashuk/inhabited_island pull request #1
Opened 2022-09-01 07:02 UTC by dmitrijgashuk

2022-09-18 13:46 UTC, akupreychik approved these changes
по проекту нужно поправить авто форматирование + твой код понятен без комментов, они тут лишние)

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +import java.util.*;
таким импортом ты тянешь весь пакет, а тебе надо пару классов)

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +        FeedingHandler feedingHandler = new FeedingHandler(gameZones);
в каждом методе ты это инициализируешь, может это можно вынести наверх?

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/DemoIsland.java
> +    private static void eatingAlgorithm(Area area) {
очень большой метод, надо разделить на маленькие + так по всему проекту

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/TestCase.java
> +    public static void main(String[] args) {
если это что-то тестовое, оно не должно быть тут

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/entity/Animal.java
> +public abstract class Animal extends Entity{
```suggestion
@Getter
public abstract class Animal extends Entity{
```

2022-09-18 13:46 UTC, akupreychik commented on src/ua/com/javarush/dhashuk/wonderisland/entity/Animal.java
> +public abstract class Animal extends Entity{
и тогда геттер будет у каждого поля и не нужно писать его над каждым полем

2022-09-27 19:39 UTC, AndryLat requested changes

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +        for (int j = 0; j < gameZones.length; j++) {
почему j и к? что они означают? дай им емкие имена.

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +                Area currentArea = areaQueue.poll();
лучше лямбдой

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +        Stream<Area> stream = Arrays.stream(gameZones).flatMap(new Function<Area[], Stream<Area>>() {
тут тоже лямбда нужна, так как ты написал никто не пишет.

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/DayProcessor.java
> +        stream.forEach(x -> areaQueue.add((Area) x));
зачем отрывать? вместо точки с запятой ставишь точку и пишешь форич.

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/DemoIsland.java
> +        gameZones[1][2] = field;
почему именно эти цифры? что тут, что дальше (5,4)

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/model/Area.java
> +                if (animal.getClass() == type) {
vожно просто вернуть условное выражение...

2022-09-27 19:39 UTC, AndryLat commented on src/ua/com/javarush/dhashuk/wonderisland/model/Island.java
> +                                e.printStackTrace();//todo
это явно не корректная обработка исключения.

2022-10-07 11:10 UTC, merged